//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.Hulamin.WinFormsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gijima.Hulamin.WinFormsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backgrund {
            get {
                object obj = ResourceManager.GetObject("Backgrund", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Backgrund1 {
            get {
                object obj = ResourceManager.GetObject("Backgrund1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hd_wallpapers_background_wallpaper_background_hd_wallpaper_background____ {
            get {
                object obj = ResourceManager.GetObject("hd wallpapers background wallpaper background hd wallpaper background ...", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string RollingProductsApp_ShowStatus_Create {
            get {
                return ResourceManager.GetString("RollingProductsApp_ShowStatus_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string RollingProductsApp_ShowStatus_Delete {
            get {
                return ResourceManager.GetString("RollingProductsApp_ShowStatus_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully!...
        /// </summary>
        internal static string RollingProductsApp_ShowStatus_Deleted_Successfully___ {
            get {
                return ResourceManager.GetString("RollingProductsApp_ShowStatus_Deleted_Successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RollingProductsApp_ShowStatus_Error {
            get {
                return ResourceManager.GetString("RollingProductsApp_ShowStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully!...
        /// </summary>
        internal static string RollingProductsApp_ShowStatus_Saved_Successfully___ {
            get {
                return ResourceManager.GetString("RollingProductsApp_ShowStatus_Saved_Successfully___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!. Please try again!...
        /// </summary>
        internal static string RollingProductsApp_ShowStatus_Something_went_wrong___Please_try_again___ {
            get {
                return ResourceManager.GetString("RollingProductsApp_ShowStatus_Something_went_wrong___Please_try_again___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string RollingProductsApp_ShowStatus_Update {
            get {
                return ResourceManager.GetString("RollingProductsApp_ShowStatus_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully!...
        /// </summary>
        internal static string RollingProductsApp_ShowStatus_Updated_Successfully___ {
            get {
                return ResourceManager.GetString("RollingProductsApp_ShowStatus_Updated_Successfully___", resourceCulture);
            }
        }
    }
}
